### ISSUE TITLE
Support AMPHTML ad

### ISSUE THREAD

**Issue by lannka** [levidurfee/ampbin#59]
**Is your feature request related to a problem? Please describe.**
This tool is so helpful to quickly demonstrate an idea or reproduce a bug etc. It will be great if it also support [AMPHTML ads](https://www.ampproject.org/docs/ads/amphtml_ads)? This can be a cool place to craft and share AMPHTML ad creatives. 

**Describe the solution you'd like**
AMPHTML ads is AMP with a different validator setup.
Other good to have feature: adjustable viewport size of the preview.

/cc @jasti

**Comment by levidurfee** [comment]
I think this is a wonderful idea. I'm currently rewriting this in TypeScript, so I'll try and implement it then.

**Comment by levidurfee** [comment]
It looks like `amp.validator.validateString()` accepts a second parameter which is used to specify the AMP HTML Format. By passing in `AMP4ADS`, it'll validate for AMPHTML ads.

**Comment by levidurfee** [comment]
I accidentally deployed it to production instead of my staging environment, but I think it's okay.

https://ampb.in/

I still need to do a few things:

* [ ] Switch starter HTML when switching between formats
* [ ] Toaster notifications
* [ ] Show Google user image
* [ ] Link help button
* [ ] adjustable viewport size of the preview

Please let me know if this helps, you have any problems, or have any other suggestions.

**Comment by lannka** [comment]
and it "accidentally" worked ! :-)

Good job! thanks for the quick turnaround!

**Comment by levidurfee** [comment]
Yayy! Closing this and opening another issue for the remaining items.
